### Create SFEIR Event
< {%
    const now = new Date(Date.now());
    const startDateTs = (new Date(now.getFullYear(), now.getMonth() + 1, now.getDate(), 1, 0, 0)).getTime();
    const endDateTs = (new Date(now.getFullYear(), now.getMonth() + 1, now.getDate() + 1, 1, 0, 0)).getTime();
    request.variables.set("sfeirEvents_startDateTs", startDateTs.toString());
    request.variables.set("sfeirEvents_endDateTs", endDateTs.toString());
%}
POST {{protocol}}{{host}}:{{port}}/v1/events
Content-Type: application/json

{
  "name": "Event created from request files - expect to fail at create",
  "startDateTs": "{{sfeirEvents_startDateTs}}",
  "endDateTimestamp": "{{sfeirEvents_endDateTs}}"
}

> {%

    client.test("Request executed unsuccessfully", function () {
        client.assert(response.status === 500, "Response status is not 500");
    });

%}

###
