name: CD

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy (e.g., v1.0.0). Leave empty to use the latest tag'
        required: false
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT_ID: ${{ vars.CI_GCP_PROJECT_ID }}
  REGION: ${{ vars.CI_GCP_PROJECT_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine tag to deploy
        id: get_tag
        run: |
          if [ -z "${{ github.event.inputs.tag }}" ]; then
            TAG=$(git describe --tags --abbrev=0)
          else
            TAG=${{ github.event.inputs.tag }}
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "Deploying tag: $TAG"

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.CI_SERVICE_ACCOUNT_CONTENT }}
          service_account: ${{ vars.CI_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Create credentials
        run: echo ${{ secrets.BACKEND_SERVICE_ACCOUNT_CONTENT }} >> ./backend/credentials.json

      - name: Build and Push Backend
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/aimagine-backend:${{ env.TAG }} -f backend/Dockerfile ./backend
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/aimagine-backend:${{ env.TAG }}

      - name: Deploy Backend to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: "aimagine-sfeirlille-backend"
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/aimagine-backend:${{ env.TAG }}
          flags: '--service-account="aimagine-sfeirlille@lil-onboard-gcp.iam.gserviceaccount.com" --allow-unauthenticated'
          env_vars: |
            HOST=${{ vars.BACKEND_HOST }}
            SWAGGER_BASE_PATH=${{ vars.BACKEND_SWAGGER_BASE_PATH }}
            CORS_ALLOWED_ORIGINS=${{ vars.BACKEND_CORS_ALLOWED_ORIGINS }}
            SQLITE_DB_PATH=${{ vars.BACKEND_SQLITE_DB_PATH }}
            EMAIL_ENCRYPTION_KEY=${{ secrets.BACKEND_EMAIL_ENCRYPTION_KEY }}
            EMAIL_ENCRYPTION_IV=${{ secrets.BACKEND_EMAIL_ENCRYPTION_IV }}
            IMAGEN_GCP_PROJECT_ID=${{ vars.BACKEND_IMAGEN_GCP_PROJECT_ID }}
            IMAGEN_REGION=${{ vars.BACKEND_IMAGEN_REGION }}
            IMAGEN_ENABLED=${{ vars.BACKEND_IMAGEN_ENABLED }}
            FIRESTORE_GCP_PROJECT_ID=${{ vars.BACKEND_FIRESTORE_GCP_PROJECT_ID }}
            FIRESTORE_ENABLED=${{ vars.BACKEND_FIRESTORE_ENABLED }}
            BUCKET_GCP_PROJECT_ID=${{ vars.BACKEND_BUCKET_GCP_PROJECT_ID }}
            BUCKET_ENABLED=${{ vars.BACKEND_BUCKET_ENABLED }}

      - name: Build and Push Public Frontend
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/aimagine-public-frontend:${{ env.TAG }} -f public-frontend/Dockerfile --build-arg VITE_BACKEND_API_URL=${{ vars.PUBLIC_FRONTEND_VITE_BACKEND_API_URL }} .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/aimagine-public-frontend:${{ env.TAG }}

      - name: Deploy Public Frontend to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: "aimagine-sfeirlille-public-frontend"
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/aimagine-public-frontend:${{ env.TAG }}
          flags: '--service-account="aimagine-sfeirlille@lil-onboard-gcp.iam.gserviceaccount.com" --allow-unauthenticated'

      - name: Build and Push Private Frontend
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/aimagine-private-frontend:${{ env.TAG }} -f private-frontend/Dockerfile --build-arg VITE_BACKEND_API_URL=${{ vars.PRIVATE_FRONTEND_VITE_BACKEND_API_URL }} --build-arg VITE_PUBLIC_FRONTEND_URL=${{ vars.PUBLIC_FRONTEND_VITE_BACKEND_API_URL }} .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/aimagine-private-frontend:${{ env.TAG }}

      - name: Deploy Private Frontend to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: "aimagine-sfeirlille-private-frontend"
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cloud-run-source-deploy/aimagine-private-frontend:${{ env.TAG }}
          flags: '--service-account="aimagine-sfeirlille@lil-onboard-gcp.iam.gserviceaccount.com" --allow-unauthenticated'
